### ISSUE TITLE
Section 508 502.3.1: (devenv/tab item 'Data') An element's IsOffScreen property must be false when its clickable point is on screen.

### ISSUE THREAD

**Issue by SaisreeDandamudi** [dotnet/machinelearning-modelbuilder#1157]
“[Check out Accessibility Insights!](https://accessibilityinsights.io/) - Identify accessibility bugs before check-in and make bug fixing faster and easier.”

### GitHubTags:
#A11yMAS; #A11yTCS; #Win32; #DesktopApp; #Feature-ML.NETModelBuilder-Win32-Nov2020; #A11ySev2; #Benchmark; #Visual Studio; #A11yAuto; #WCAG4.2.1;

### Environment Details:
Microsoft Visual Studio 2019 Preview Version 16.8.0 Preview 6.0

### Repro Steps:

1.Open Visual Studio Enterprise 2019 Preview 
2. Create a new .Net Core Console App (C#) 
3. Tab to "Solution Explorer" and right click on the project (Shift + F10) and then from the expanded list Select "Add" and then from the list items select "Machine learning"
4.Tab till "Text Classification" scenario and select it
5.tab till "next" button and press enter
6. Select the data source type and upload the data file
7. Now run Accessibility Insights for Windows on the screen

The following accessibility issue needs investigation.

### App: 
devenv

### Element path:
tab item 'Data'

### Issue Details:
 An element's IsOffScreen property must be false when its clickable point is on screen. [Section 508 502.3.1](https://www.access-board.gov/guidelines-and-standards/communications-and-it/about-the-ict-refresh/final-rule/single-file-version#502-interoperability-assistive-technology)

### How To Fix:
 If the element's ClickablePoint property is correct, set the element's IsOffScreen property to false.
If the element's ClickablePoint property is incorrect, please ensure it returns the correct value.

This accessibility issue was found using Accessibility Insights for Windows, a tool that helps debug and find accessibility issues earlier. Get more information and download this tool at https://aka.ms/AccessibilityInsights.
![1157_ML  NET_An element IsOffScreen property must be false when its clickable point is on screen](https://user-images.githubusercontent.com/51435580/101602939-e202cc80-3a24-11eb-9a05-e76616ac0d80.png)

**Comment by beccamc** [comment]
Is this a problem with the VS shell (part of VS itself)? Or part of Model Builder? Based on the screenshot this looks like a problem in VS and not in our product?

**Comment by beccamc** [comment]
Oh never mind, I see now that the screen is scrolled down 😄

**Comment by zewditu** [comment]
This issue is solved in .Net Framework 4.8 . we  need to consider to use  Accessibility switches(https://microsoft.sharepoint.com/sites/accessibility/Lists/MASProblemsAndSuggestedFixes/DispForm.aspx?ID=335)  to leverage new accessibility fixes in  .Net Framework 4.8

**Comment by zewditu** [comment]
If model Builder stop to support VS 2017, we can upgrade into 4.8  and leverage the accessibility fix in it.

**Comment by beccamc** [comment]
Here is the build for testing https://devdiv.visualstudio.com/_apis/resources/Containers/7859052/VSSetup.Dev16Insertion?itemPath=VSSetup.Dev16Insertion%2FMicrosoft.ML.ModelBuilder.vsix

**Comment by beccamc** [comment]
vzhuqin, you don't need to verify this one. @SaisreeDandamudi from the accessibility team will need to verify and close this. Thanks!

**Comment by SaisreeDandamudi** [comment]
@beccamc I have verified the bug by downloading the above build and the issue still re-pros. can you please look into it
ML .NET model builder Version: 16.6.0.2130907
Microsoft Visual Studio Enterprise 2019 Preview
Version 16.11.0 Preview 1.0

**Comment by zewditu** [comment]
@SaisreeDandamudi, could you test on 4.8 target framework?

**Comment by SaisreeDandamudi** [comment]
@beccamc @zewditu I have tested on .net 4.8 framework and the issue still re-pros

**Comment by zewditu** [comment]
@SaisreeDandamudi  did you installed .NET framework 4.8 ?

**Comment by SaisreeDandamudi** [comment]
@zewditu Yes.. I am using .Net framework 4.8
![image](https://user-images.githubusercontent.com/51435580/122632212-008e0280-d0ef-11eb-864b-a432acfc39e7.png)

**Comment by zewditu** [comment]
@SaisreeDandamudi  thanks to  let us know.

**Comment by zewditu** [comment]
Closed because this issue is a know WPF issue and Tracked with [1161493](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1161493/) and It won't be fixed until .Net 6.

**Comment by beccamc** [comment]
Just to add some more context here. The related [MAS problem](https://microsoft.sharepoint.com/sites/accessibility/Lists/MASProblemsAndSuggestedFixes/DispForm.aspx?ID=335) states:

> If the issue relates to WPF ListView items that are scrolled out of view, this issue is being tracked with [1161493](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1161493/): "Inconsistent UIA IsOffscreen and ClickablePoint properties for WPF ListViewItems that are scrolled out of view". **While that bug is active, it is recommended that apps which have related bugs open against them, those app bugs can be resolved as External with a link to the tracking WPF bug.**

We got confirmation from Sam Bent that our problem with the TabControl is the same issue as the above ListView problem. We are resolving this as External.

**Comment by poojapatil36** [comment]
Verified the issue in below version.
Microsoft Visual Studio Enterprise 2022 (64-bit) - Current
Version 17.4.4
Issue is not reproducing, please find below attachment for reference.
Github tag: #Closed;
![1157_Section 508 502 3 1](https://user-images.githubusercontent.com/97668775/218068820-cdff465f-1bf1-47a2-869e-85fcc2fd3c73.png)
