### ISSUE TITLE
The sample project "SampleClassification.ConsoleApp" run error.

### ISSUE THREAD

**Issue by vzhuqin** [dotnet/machinelearning-modelbuilder#1405]
**System Information (please complete the following information):**
- Windows 10 Enterprise, Version 20H2
- ML.Net Model Builder (Preview): 16.5.0.2115505
- Microsoft Visual Studio Enterprise 2019: 16.9.3
- .Net: 5.0.201
- MLNET (Preview): 16.5.17

**To Reproduce**
1. Install MLNET with the command: dotnet tool install mlnet -g --add-source https://mlnetcli.blob.core.windows.net/mlnetcli/index.json --version 16.5.17
2. Copy yelp_labelled.txt to one folder;
[yelp_labelled.txt](https://github.com/dotnet/machinelearning-modelbuilder/files/6335255/yelp_labelled.txt)

3. Go to the folder and run command: mlnet classification --dataset "yelp_labelled.txt" --label-col 1 --has-header false --train-time 10
4. Go to the sample project by running command: cd sampleclassification
5. Enter command: dotnet run
6. See error as below screenshot.

**Expected behavior**
no error during dotnet run

**Screenshots**
![image](https://user-images.githubusercontent.com/81727020/115221850-adbebb80-a13c-11eb-81d1-e89e5d1519fc.png)

**Additional context**
https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/sentiment-analysis-cli

**Comment by LittleLittleCloud** [comment]
It's a known bug and should be fixed in preview release already
https://github.com/dotnet/machinelearning-modelbuilder/issues/1137

**Comment by vzhuqin** [comment]
@LittleLittleCloud  I tried to replace the line of SampleClassification.ConsoleApp.consumption.cs mentioned in the issue https://github.com/dotnet/machinelearning-modelbuilder/issues/1137, but still cannot "dotnet run" successfully, could you help to take a look where I did wrong when you are available?

Tried one: 
Replace the line: 
private static string MLNetModelPath = Path.GetFullPath("SampleClassification.ConsoleApp.zip");
with:
private static string MLNetModelPath = Path.Combine(System.AppContext.BaseDirectory, "SampleClassification.ConsoleApp.zip");
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/0d10505d-72ed-43c9-99f0-bd586c020bd4)

Tried two: 
Replace the line: 
private static string MLNetModelPath = Path.GetFullPath("SampleClassification.ConsoleApp.zip");
with:
public static string MLNetModelPath = Path.Combine(System.AppContext.BaseDirectory, "SampleClassification.ConsoleApp.zip");

![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/900e019b-0f19-4f47-8e88-025ac131e94c)
Content in SampleClassification folder:
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/49babc76-7566-4856-8e15-143af285c91e)

SampleClassification.ConsoleApp.consumption.cs file:
[https://app.zenhub.com/files/186917455/a015839d-0265-4207-bf74-39f5deeb4d0e/download](https://app.zenhub.com/files/186917455/a015839d-0265-4207-bf74-39f5deeb4d0e/download)

**Comment by LittleLittleCloud** [comment]
Hi @vzhuqin 
It looks like a build error, can you try with a sanitized name, like "SampleClassification_ConsoleApp" instead of "SampleClassification.ConsoleApp"? (replacing '.' with '_' so it follow C# syntax)

**Comment by LittleLittleCloud** [comment]
>Hi @vzhuqin
It looks like a build error, can you try with a sanitized name, like "SampleClassification_ConsoleApp" instead of "SampleClassification.ConsoleApp"? (replacing '.' with '_' so it follow C# syntax)

I'll create another issue for this error. The class name should be sanitized in code generator

**Comment by vzhuqin** [comment]
Hi @LittleLittleCloud, I tired on mlnet version: 16.5.25, still occurs error as below screenshot, could you help to take a look?

**Steps:**
1. Run Commend: mlnet classification --dataset "yelp_labelled.txt" --label-col 1 --has-header false --train-time 10 --name SampleClassification0521
2. Rename to "SampleClassification0521ConsoleApp" from "SampleClassification0521.ConsoleApp"
3. Run commend: dotnet run

**Screenshot:**
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/6fe5fe67-5e10-40f0-b6c4-de3e112495df)

**Comment by vzhuqin** [comment]
This issue not occurs on mlnet version: 16.6.1

Steps:
1. Install mlnet using the command: dotnet tool install mlnet -g --add-source https://mlnetcli.blob.core.windows.net/mlnetcli/index.json
2. Copy yelp_labelled.txt to one folder named: 1405
3. Go to the folder and run command: mlnet classification --dataset "yelp_labelled.txt" --label-col 1 --has-header false --train-time 60
4. Go to the generated folder: SampleClassification and use VS to open the project: SampleClassification.ConsoleApp.csproj
5. Open model builder in VS and navigate to Consume page;
6. Click "Add to solution" button after Console app to add one ConsoleApp project;
7. Can run the console app project in VS;
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/4b8b6795-b1b8-4508-8e91-d16d3f217683)
8. Can "dotnet run" the console app project in CLI.
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/2800be62-3636-40e5-a516-8ddcf7674aef)
