### ISSUE TITLE
Recommendation: Non-Label/Item/User columns should be "Ignore"

### ISSUE THREAD

**Issue by v-Hailishi** [dotnet/machinelearning-modelbuilder#2296]
**System Information (please complete the following information):**
Windows OS: Windows-11-Enterprise-21H2
ML.Net Model Builder 2022: 16.13.10.2251801 (Main Build)
Microsoft Visual Studio Enterprise: 2022(17.3.6)
.Net: 6.0

**Describe the bug**
- On which step of the process did you run into an issue: 
Training should be failed after changing the feature column 's Data type from "Single" to "Boolean".

**Data Source**
https://testpass.blob.core.windows.net/test-pass-data/recommendation-ratings.csv

**To Reproduce**

  1. Select Create a new project from the Visual Studio 2022 start window.
  2. Choose the C# Console App (.NET Core6.0) project template.
  3. Add model builder by right click on the project.
  4. Select **Recommendation** scenario.
  5. On Data page, select the data source and choose "rating" as Label, "userId" as User, "movieId" as Item.
  6. Change "timestamp" column's Data type from "Single" to "Boolean".
  7. On the Train page, you will see that training is completed successfully.

**Expected behavior**
Training should be failed.

**Screenshot**
![image](https://user-images.githubusercontent.com/99375895/196614484-4c622776-e142-4b12-8dba-b18003b93be8.png)

**Additional context:**

**Comment by beccamc** [comment]
Timestamp is automatically ignored in this case. All other columns in recommendation training are ignored. 

@luisquintanilla Do you think the fact the other columns are ignored should be better advertised to the user?

**Comment by luisquintanilla** [comment]
> @luisquintanilla Do you think the fact the other columns are ignored should be better advertised to the user?

@beccamc good question. While @zewditu and I were looking at some of the other scenarios, our "Ignore" behavior wasn't clear. When the column purpose is set to "Ignore", it removes it from the dropdowns in the main Data screen but I believe it still is part of codegen and Try It Out experiences. Similar to this case, since columns not selected as the Id columns are automatically ignored. In both cases, to me it doesn't sound right or at the very least to your point it's unclear what the behavior is. Let's set up some time to better understand what the Ignore behavior is and try to make it more consistent.

Related to #2115

**Comment by beccamc** [comment]
SQL "Ignore GUID columns" is resolved (1504)! Unfortunately It looks like the ignored column values are still being used for sample data and evaluate for text files (2155). 

It seems like we should do two things...
- [ ] Set all non label/user/item columns as "Ignore" for recommendation scenario
- [ ] Make sure ignored columns aren't used for evaluate/consume for all scenarios. 

I believe #1756 only applies to ignored columns in the data preview and doesn't apply to this.

**Comment by luisquintanilla** [comment]
That was easy 🙂 

I'm okay with that action plan.

**Comment by v-Hailishi** [comment]
Verified on the latest main build 16.14.0.2252604, the error message has been changed to "Version string portion was too short or too long."
Besides, after change "userId" or "movieId" or "timestamp" column's Data type from "Single" to "String", it will also train failed with this error message.
![image](https://user-images.githubusercontent.com/99375895/198175063-2c225ded-5a4a-4ed3-9db8-fb21284d77e1.png)

**Comment by beccamc** [comment]
Set all non label/user/item columns as "Ignore" for recommendation scenario. Same for Forecasting scenario AND Text Classification.

**Comment by luisquintanilla** [comment]
This issue isn't completely fixed. 

-  Set all non label/user/item columns as "Ignore" for recommendation scenario. Same for Forecasting scenario. - this issue is the last item pending.

**Comment by v-Hailishi** [comment]
The bug has been fixed on the latest main build: 16.14.2.2306101

- Recommendation:

<img width="521" alt="image" src="https://user-images.githubusercontent.com/99375895/212042945-78940b2d-2ee6-4cb0-baf3-8a2d78deebd1.png">
<img width="266" alt="image" src="https://user-images.githubusercontent.com/99375895/212042991-f93ed9a3-74b0-49b9-a144-02f83dbebc26.png">
<img width="624" alt="image" src="https://user-images.githubusercontent.com/99375895/212043248-05d01d2a-7587-4fda-852e-cf4b5ce01366.png">
<img width="538" alt="image" src="https://user-images.githubusercontent.com/99375895/212043555-e4cdd9de-fe78-45f2-b237-8c269924e73c.png">

- Text classification:

<img width="519" alt="image" src="https://user-images.githubusercontent.com/99375895/212049828-0dfa25e5-801c-45f5-9bff-3c109ece6abf.png">
<img width="423" alt="image" src="https://user-images.githubusercontent.com/99375895/212049899-aee4b9cc-c779-43d9-8836-0dc2c8ab5816.png">
<img width="576" alt="image" src="https://user-images.githubusercontent.com/99375895/212050551-77bc14f4-a9b3-4e80-be7f-f32c7e8bce34.png">
<img width="534" alt="image" src="https://user-images.githubusercontent.com/99375895/212050612-ea5d947f-423f-4076-8cdb-83da653118be.png">
