### ISSUE TITLE
Data classification&Value predication: Training failed with error "Object reference not set to an instance of an object." when only choosing "LGBM" algorithm to train "Tabular File" data source.

### ISSUE THREAD

**Issue by v-Hailishi** [dotnet/machinelearning-modelbuilder#2733]
**System Information (please complete the following information):**
Windows OS: Windows-11-Enterprise-22H2
ML.Net Model Builder 2022: 17.17.0.2332602 (Main Build)
Microsoft Visual Studio Enterprise: 2022(17.5.5)
.Net: 6.0, 7.0

**Describe the bug**
- On which step of the process did you run into an issue: 
Training failed with error "Object reference not set to an instance of an object." when only choosing "LGBM" algorithm.

**TestMatrix**
https://testpass.blob.core.windows.net/test-pass-data/wikipedia-detox-250-line-data.tsv
https://testpass.blob.core.windows.net/test-pass-data/taxi-fare.csv

**To Reproduce**
  1. Select Create a new project from the Visual Studio start window.
  2. Choose the C# Console App (.NET Core) project template.
  3. Add model builder by right click on the project.
  4. Select **Data classification or Value predication** scenario.
  5. On Data page, choose the "Tabular File" data source.
  6. On the Train page, click the "Advanced training options..." link.
  7. Go to "Trainers" tab, only choose "**LGBM**" algorithm and save it.
  8. The training would be failed with error "Object reference not set to an instance of an object.".
  
**Expected behavior**
Training successfully.

**Screenshot**
![image](https://github.com/dotnet/machinelearning-modelbuilder/assets/99375895/506cbba6-dfe9-4c79-afa2-28feca4f9e86)
![image](https://github.com/dotnet/machinelearning-modelbuilder/assets/99375895/2024d03c-4ad2-4d28-ab13-d50dceb3c2f9)

**Additional context**
The bug is **not repro** when choosing "LGBM" algorithm to train SQL Server data.

**Comment by v-Hailishi** [comment]
The bug has been fixed on the latest main build 17.17.0.2335401.
![image](https://github.com/dotnet/machinelearning-modelbuilder/assets/99375895/ce35654a-eddc-4e10-a501-f3e1e4d66003)

**Comment by v-Hailishi** [comment]
The bug is repro again on the latest main build 17.17.0.2336302.
![image](https://github.com/dotnet/machinelearning-modelbuilder/assets/99375895/6c46412d-dcbf-4d6d-bb5f-a73a786613ff)

**Comment by DMackAttack132** [comment]
how do I get the latest version (17.17.0.2335401)? I only see 17.17.0.2332602

**Comment by DMackAttack132** [comment]
> 17.17.0.2335401 is the internal version for our tester. We haven't released the fixed version yet.

Looking for an update on this. Has the fix been released? I'm still having this issue.

**Comment by mgamache** [comment]
having the same issue, is there any ETA on this?
