### ISSUE TITLE
All scenarios: Training failed with error "Value cannot be null. (Parameter 'providerFactory')" when choosing SQL Server data source.

### ISSUE THREAD

**Issue by v-Hailishi** [dotnet/machinelearning-modelbuilder#2900]
**System Information (please complete the following information):**
Windows OS: Windows-11-Enterprise-23H2
ML.Net Model Builder 2022: 17.18.2.2421201 (Main Build)
Microsoft Visual Studio Enterprise: 2022(17.9.6)
.Net Core: 6.0,7.0,8.0

**Describe the bug**
- On which step of the process did you run into an issue: 
All scenarios: Training failed with error "Value cannot be null. (Parameter 'providerFactory')" when choosing SQL Server data source.

**TestMatrix**
https://github.com/dotnet/machinelearning-modelbuilder/files/10534387/home-depot-sentence-similarity-small.csv

**To Reproduce**

1. Select Create a new project from the Visual Studio start window.
2. Choose the C# Console App (.NET Core) project template.
3. Add model builder by right click on the project.
4. Select any scenario.
5. On the Data page, choose the SQL Server data source.
6. On the Train page, click "Start training" button, you will see that the training failed.

**Expected behavior**
Training successful.

**Screenshot:**
![image](https://github.com/dotnet/machinelearning-modelbuilder/assets/99375895/5c152c8d-3298-46e9-a710-9f30c2a91c4a)
![image](https://github.com/dotnet/machinelearning-modelbuilder/assets/99375895/99b95bf1-d24a-4e3c-b707-7bf11339ffae)

**Additional context:**
The bug is not repro when choosing File data source.

**Comment by v-Hailishi** [comment]
The bug has been fixed on the latest main build 17.18.3.2421901.
![image](https://github.com/dotnet/machinelearning-modelbuilder/assets/99375895/3001bb1a-4048-42e0-819b-4b29ec870f61)

**Comment by sphengle** [comment]
> The bug has been fixed on the latest main build 17.18.3.2421901. ![image](https://github.com/dotnet/machinelearning-modelbuilder/assets/99375895/3001bb1a-4048-42e0-819b-4b29ec870f61)

How do you update ML.NET?

**Comment by v-Hailishi** [comment]
@sphengle The main build is the unpublished build for testing.
You can download the latest release build from https://marketplace.visualstudio.com/items?itemName=MLNET.ModelBuilder2022

**Comment by sphengle** [comment]
> [@sphengle](https://github.com/sphengle) The main build is the unpublished build for testing. You can download the latest release build from https://marketplace.visualstudio.com/items?itemName=MLNET.ModelBuilder2022

Seems I already have this version.  But still getting the same error.

**Comment by v-Hailishi** [comment]
@sphengle The bug is repro again, there is a new bug https://github.com/dotnet/machinelearning-modelbuilder/issues/3005 to tracking it.
